export type MenuItem = {
  id: string;
  name: string;
  category: string;
  subCategory?: string;
  isVeg: boolean;
  calories: number;
  price: string; // e.g. "280" or "280/370" for half/full
  description?: string;
  tags?: string[];
};

export const CATEGORIES = [
  "All",
  "Soups",
  "Starters",
  "Main Course",
  "Biryani & Rice",
  "Breads",
  "Lentils",
  "Oriental",
  "Noodles",
  "Thali",
  "Rice Bowl",
  "Combo Meals",
  "Sizzlers",
  "Marinades",
  "Drinks",
];

export const FILTERS = [
  { label: "All", value: "all" },
  { label: "Veg", value: "veg" },
  { label: "Non-Veg", value: "nonveg" },
  { label: "Soups", value: "Soups" },
  { label: "Starters", value: "Starters" },
  { label: "Main Course", value: "Main Course" },
  { label: "Biryani", value: "Biryani & Rice" },
  { label: "Oriental", value: "Oriental" },
  { label: "Noodles", value: "Noodles" },
  { label: "Thali", value: "Thali" },
  { label: "Breads", value: "Breads" },
  { label: "Combo Meals", value: "Combo Meals" },
  { label: "Drinks", value: "Drinks" },
];

export const menuItems: MenuItem[] = [
  // ───── SOUPS N SHORBA ─────
  { id: "s1", name: "Cream Soup (Tomato/Veg/Mushroom)", category: "Soups", isVeg: true, calories: 120, price: "140" },
  { id: "s2", name: "Murgh Shorba", category: "Soups", isVeg: false, calories: 95, price: "170" },
  { id: "s3", name: "Mutton Paya Shorba", category: "Soups", isVeg: false, calories: 180, price: "180" },
  { id: "s4", name: "Sweetcorn Veg", category: "Soups", isVeg: true, calories: 150, price: "140" },
  { id: "s5", name: "Sweetcorn Chicken", category: "Soups", isVeg: false, calories: 180, price: "175" },
  { id: "s6", name: "Hot n Sour Veg", category: "Soups", isVeg: true, calories: 110, price: "140" },
  { id: "s7", name: "Hot n Sour Chicken", category: "Soups", isVeg: false, calories: 140, price: "175" },
  { id: "s8", name: "Manchow Veg", category: "Soups", isVeg: true, calories: 130, price: "150" },
  { id: "s9", name: "Manchow Chicken", category: "Soups", isVeg: false, calories: 160, price: "180" },
  { id: "s10", name: "Thukpa Veg", category: "Soups", isVeg: true, calories: 200, price: "220" },
  { id: "s11", name: "Thukpa Chicken", category: "Soups", isVeg: false, calories: 240, price: "260" },
  { id: "s12", name: "Lemon Coriander Veg", category: "Soups", isVeg: true, calories: 80, price: "180" },
  { id: "s13", name: "Lemon Coriander Chicken", category: "Soups", isVeg: false, calories: 110, price: "210" },
  { id: "s14", name: "Prawn n Noodle", category: "Soups", isVeg: false, calories: 220, price: "250" },

  // ───── STARTERS (N.VEG) ─────
  { id: "nv1", name: "Murgh Tandoori", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 320, price: "325/575", tags: ["Tandoor"] },
  { id: "nv2", name: "Murgh Afghani", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 380, price: "350/610", tags: ["Tandoor"] },
  { id: "nv3", name: "Murgh Tikka", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 320, price: "350", tags: ["Tandoor"] },
  { id: "nv4", name: "Murgh Malai Tikka", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 380, price: "380", tags: ["Tandoor"] },
  { id: "nv5", name: "Murgh Haryali Tikka", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 300, price: "350", tags: ["Tandoor"] },
  { id: "nv6", name: "Murgh Lehsuni Tikka", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 310, price: "380", tags: ["Tandoor"] },
  { id: "nv7", name: "Murgh Afghani Tikka", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 360, price: "380", tags: ["Tandoor"] },
  { id: "nv8", name: "Tandoori Egg (4pc)", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 280, price: "250" },
  { id: "nv9", name: "Mutton Shaami Kabab (6pc)", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 420, price: "380", tags: ["Kabab"] },
  { id: "nv10", name: "Mutton Seekh Kabab (2pc)", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 280, price: "380", tags: ["Kabab"] },
  { id: "nv11", name: "Chicken Seekh Kabab (2pc)", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 240, price: "300", tags: ["Kabab"] },
  { id: "nv12", name: "Crab Claws (6pc)", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 200, price: "280", tags: ["Seafood"] },
  { id: "nv13", name: "Surmai Fry (4pc)", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 360, price: "480", tags: ["Seafood"] },
  { id: "nv14", name: "Fish Tikka (6pc)", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 380, price: "420", tags: ["Seafood", "Tandoor"] },
  { id: "nv15", name: "Fish Finger (10pc)", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 450, price: "380", tags: ["Seafood"] },
  { id: "nv16", name: "Tandoori Egg & Mushroom", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 220, price: "250", tags: ["Tandoor"] },
  { id: "nv17", name: "Non Veg Platter (21pc)", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 900, price: "1199", tags: ["Platter", "Bestseller"] },
  { id: "nv18", name: "Seafood Platter (21pc)", category: "Starters", subCategory: "Non-Veg", isVeg: false, calories: 850, price: "1399", tags: ["Platter", "Seafood"] },

  // ───── STARTERS (VEG) ─────
  { id: "v1", name: "Paneer Angare (6pc)", category: "Starters", subCategory: "Veg", isVeg: true, calories: 380, price: "370", tags: ["Tandoor"] },
  { id: "v2", name: "Paneer Haryali Tikka (6pc)", category: "Starters", subCategory: "Veg", isVeg: true, calories: 360, price: "370", tags: ["Tandoor"] },
  { id: "v3", name: "Paneer Afghani Tikka (6pc)", category: "Starters", subCategory: "Veg", isVeg: true, calories: 400, price: "390", tags: ["Tandoor"] },
  { id: "v4", name: "Paneer Malai Tikka (6pc)", category: "Starters", subCategory: "Veg", isVeg: true, calories: 420, price: "390", tags: ["Tandoor"] },
  { id: "v5", name: "Hara Bhara Kabab (8pc)", category: "Starters", subCategory: "Veg", isVeg: true, calories: 320, price: "300", tags: ["Kabab"] },
  { id: "v6", name: "Tandoori Soya Chaap (10pc)", category: "Starters", subCategory: "Veg", isVeg: true, calories: 380, price: "300", tags: ["Tandoor"] },
  { id: "v7", name: "Afghani Soya Chaap (10pc)", category: "Starters", subCategory: "Veg", isVeg: true, calories: 400, price: "310" },
  { id: "v8", name: "Veg Shaami Kabab (6pc)", category: "Starters", subCategory: "Veg", isVeg: true, calories: 280, price: "300", tags: ["Kabab"] },
  { id: "v9", name: "Veg Tandoori Platter (21pc)", category: "Starters", subCategory: "Veg", isVeg: true, calories: 750, price: "899", tags: ["Platter"] },

  // ───── MAIN COURSE (VEG) ─────
  { id: "mc1", name: "Paneer Makhani", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 420, price: "280/370", tags: ["Bestseller"] },
  { id: "mc2", name: "Paneer Tikka Masala", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 440, price: "280/370" },
  { id: "mc3", name: "Paneer Bhurji", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 380, price: "300/400" },
  { id: "mc4", name: "Mutter Paneer", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 360, price: "210/350" },
  { id: "mc5", name: "Paneer Masala", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 400, price: "280/370" },
  { id: "mc6", name: "Paneer Saagwala", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 340, price: "240/350" },
  { id: "mc7", name: "Paneer Jhalfrezi", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 380, price: "295/390" },
  { id: "mc8", name: "Kadhai Paneer", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 420, price: "280/370" },
  { id: "mc9", name: "Shahi Paneer", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 480, price: "345/420", tags: ["Rich"] },
  { id: "mc10", name: "Paneer Pasanda", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 500, price: "345/420" },
  { id: "mc11", name: "Methi Mutter Malai", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 340, price: "210/300" },
  { id: "mc12", name: "Subz Jhalfrezi", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 280, price: "210/310" },
  { id: "mc13", name: "Veg Handi", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 300, price: "210/310" },
  { id: "mc14", name: "Aloo Bhaja", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 200, price: "80/125" },
  { id: "mc15", name: "Soya Chaap Masala", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 380, price: "240/350" },
  { id: "mc16", name: "Veg Bhuna", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 320, price: "275/320" },
  { id: "mc17", name: "Veg Hyderabadi", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 310, price: "220/315" },
  { id: "mc18", name: "Jeera Aloo", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 220, price: "150/225" },
  { id: "mc19", name: "Aloo Gobi", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 240, price: "170/250" },
  { id: "mc20", name: "Mushroom Masala", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 280, price: "240/350" },
  { id: "mc21", name: "Mutter Mushroom", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 270, price: "225/320" },
  { id: "mc22", name: "Veg Korma", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 380, price: "225/320" },
  { id: "mc23", name: "Corn Palak", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 260, price: "150/225" },
  { id: "mc24", name: "Chole Bhature", category: "Main Course", subCategory: "Veg", isVeg: true, calories: 550, price: "190", tags: ["Bestseller"] },

  // ───── MAIN COURSE (N.VEG) ─────
  { id: "mn1", name: "Gosht Roganjosh", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 450, price: "300/500", tags: ["Bestseller"] },
  { id: "mn2", name: "Bhuna Gosht", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 420, price: "300/500" },
  { id: "mn3", name: "Mutton Handi", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 500, price: "450/700" },
  { id: "mn4", name: "Mutton Korma", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 480, price: "285/450" },
  { id: "mn5", name: "Mutton Hari Mirch Dhaniya", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 440, price: "285/400" },
  { id: "mn6", name: "Mutton Do Pyaza", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 460, price: "285/400" },
  { id: "mn7", name: "Mutton Curry", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 430, price: "285/400" },
  { id: "mn8", name: "Mutton Seekh Kabab Masala", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 420, price: "285/450" },
  { id: "mn9", name: "Chicken Korma", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 420, price: "270/430" },
  { id: "mn10", name: "Chicken Tikka Lababdar", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 440, price: "285/450" },
  { id: "mn11", name: "Chicken Lehsuni", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 380, price: "270/430" },
  { id: "mn12", name: "Chicken Tikka Masala", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 460, price: "285/450", tags: ["Bestseller"] },
  { id: "mn13", name: "Chicken Makhani", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 480, price: "410/600", tags: ["Bestseller"] },
  { id: "mn14", name: "Murgh Mussallum", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 600, price: "450/650" },
  { id: "mn15", name: "Chicken Afghani Masala", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 440, price: "285/450" },
  { id: "mn16", name: "Chicken Kadhai", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 400, price: "270/430" },
  { id: "mn17", name: "Chicken Handi", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 480, price: "425/600" },
  { id: "mn18", name: "Chicken Dhaniya Mirch", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 420, price: "285/380" },
  { id: "mn19", name: "Chicken Seekh Kabab Masala", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 400, price: "270/400" },
  { id: "mn20", name: "Jhinga Masala", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 350, price: "295/475", tags: ["Seafood"] },
  { id: "mn21", name: "Fish Curry", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 320, price: "295/475", tags: ["Seafood"] },
  { id: "mn22", name: "Egg Curry (2 eggs)", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 280, price: "190" },
  { id: "mn23", name: "Egg Bhurji Masala", category: "Main Course", subCategory: "Non-Veg", isVeg: false, calories: 310, price: "175/190" },

  // ───── LENTILS ─────
  { id: "l1", name: "Dal Tadka", category: "Lentils", isVeg: true, calories: 280, price: "160/260" },
  { id: "l2", name: "Dal Makhni", category: "Lentils", isVeg: true, calories: 340, price: "190/290", tags: ["Bestseller"] },
  { id: "l3", name: "Dal Fry", category: "Lentils", isVeg: true, calories: 260, price: "150/250" },
  { id: "l4", name: "Rajma Masala", category: "Lentils", isVeg: true, calories: 320, price: "170/270" },
  { id: "l5", name: "Chole Amritsari", category: "Lentils", isVeg: true, calories: 380, price: "135/230" },

  // ───── INDIAN BREADS ─────
  { id: "b1", name: "Garlic Naan", category: "Breads", isVeg: true, calories: 220, price: "50" },
  { id: "b2", name: "Butter Naan", category: "Breads", isVeg: true, calories: 200, price: "40" },
  { id: "b3", name: "Plain Naan", category: "Breads", isVeg: true, calories: 180, price: "30" },
  { id: "b4", name: "Garlic Butter Naan", category: "Breads", isVeg: true, calories: 240, price: "60" },
  { id: "b5", name: "Malabari Parotha", category: "Breads", isVeg: true, calories: 280, price: "65" },
  { id: "b6", name: "Laccha Paratha", category: "Breads", isVeg: true, calories: 250, price: "50" },
  { id: "b7", name: "Pudina Paratha", category: "Breads", isVeg: true, calories: 260, price: "60" },
  { id: "b8", name: "Aloo Paratha", category: "Breads", isVeg: true, calories: 280, price: "85" },
  { id: "b9", name: "Missi Roti", category: "Breads", isVeg: true, calories: 180, price: "40" },
  { id: "b10", name: "Butter Tandoori Roti", category: "Breads", isVeg: true, calories: 160, price: "25" },
  { id: "b11", name: "Plain Tandoori Roti", category: "Breads", isVeg: true, calories: 150, price: "20" },
  { id: "b12", name: "Keema Paratha", category: "Breads", isVeg: false, calories: 380, price: "150" },
  { id: "b13", name: "Tawa Paratha Aloo", category: "Breads", isVeg: true, calories: 280, price: "90" },
  { id: "b14", name: "Tawa Paratha Paneer", category: "Breads", isVeg: true, calories: 300, price: "100" },
  { id: "b15", name: "Tawa Paratha Gobi", category: "Breads", isVeg: true, calories: 260, price: "80" },
  { id: "b16", name: "Roti Basket (10pc)", category: "Breads", isVeg: true, calories: 800, price: "400" },
  { id: "b17", name: "Bhature", category: "Breads", isVeg: true, calories: 280, price: "40" },

  // ───── BIRYANI & RICE ─────
  { id: "r1", name: "Sada Basmati Rice", category: "Biryani & Rice", isVeg: true, calories: 200, price: "90/140" },
  { id: "r2", name: "Jeera Rice", category: "Biryani & Rice", isVeg: true, calories: 220, price: "100/140" },
  { id: "r3", name: "Veg Pulao", category: "Biryani & Rice", isVeg: true, calories: 320, price: "185" },
  { id: "r4", name: "Paneer Pulao", category: "Biryani & Rice", isVeg: true, calories: 400, price: "240" },
  { id: "r5", name: "Peas Pulao", category: "Biryani & Rice", isVeg: true, calories: 310, price: "180" },
  { id: "r6", name: "Dal Khichdi", category: "Biryani & Rice", isVeg: true, calories: 340, price: "175" },
  { id: "r7", name: "Chicken Pulao", category: "Biryani & Rice", isVeg: false, calories: 420, price: "240" },
  { id: "r8", name: "Prawn Pulao", category: "Biryani & Rice", isVeg: false, calories: 380, price: "300", tags: ["Seafood"] },
  { id: "r9", name: "Awadhi Biryani", category: "Biryani & Rice", isVeg: false, calories: 580, price: "295/530", tags: ["Bestseller"] },
  { id: "r10", name: "Donne Biryani", category: "Biryani & Rice", isVeg: false, calories: 560, price: "280/540" },
  { id: "r11", name: "Bombay Biryani", category: "Biryani & Rice", isVeg: false, calories: 590, price: "300/575" },
  { id: "r12", name: "Thalessary Biryani", category: "Biryani & Rice", isVeg: false, calories: 570, price: "300/575" },
  { id: "r13", name: "Kolkata Biryani", category: "Biryani & Rice", isVeg: false, calories: 560, price: "295/520" },
  { id: "r14", name: "Tandoori Biryani", category: "Biryani & Rice", isVeg: false, calories: 600, price: "295/530", tags: ["Bestseller"] },
  { id: "r15", name: "Chicken Seekh Biryani", category: "Biryani & Rice", isVeg: false, calories: 530, price: "230/520" },
  { id: "r16", name: "Chicken Tikka Biryani", category: "Biryani & Rice", isVeg: false, calories: 580, price: "280/540" },
  { id: "r17", name: "Chicken Kofta Biryani", category: "Biryani & Rice", isVeg: false, calories: 570, price: "280/540" },
  { id: "r18", name: "Mutton Biryani", category: "Biryani & Rice", isVeg: false, calories: 640, price: "400/620", tags: ["Bestseller"] },
  { id: "r19", name: "Mutton Seekh Biryani", category: "Biryani & Rice", isVeg: false, calories: 610, price: "250/500" },
  { id: "r20", name: "Egg Biryani", category: "Biryani & Rice", isVeg: false, calories: 440, price: "180/250" },
  { id: "r21", name: "Paneer Tikka Biryani", category: "Biryani & Rice", isVeg: true, calories: 500, price: "225/420" },
  { id: "r22", name: "Hyderabadi Biryani (Veg)", category: "Biryani & Rice", isVeg: true, calories: 520, price: "225/420" },
  { id: "r23", name: "Donne Biryani (Veg)", category: "Biryani & Rice", isVeg: true, calories: 460, price: "225/420" },
  { id: "r24", name: "Bombay Biryani (Veg)", category: "Biryani & Rice", isVeg: true, calories: 470, price: "225/400" },
  { id: "r25", name: "Thalessary Biryani (Veg)", category: "Biryani & Rice", isVeg: true, calories: 450, price: "225/400" },

  // ───── SIZZLERS ─────
  { id: "sz1", name: "Lollypop Sizzler", category: "Sizzlers", isVeg: false, calories: 650, price: "420", description: "4 Lollypop in Schezwan sauce, Chicken noodles, Fried Egg, Crispy Mushroom" },
  { id: "sz2", name: "Tandoori Murgh Sizzler", category: "Sizzlers", isVeg: false, calories: 700, price: "460", description: "4 pieces of Tandoori Chicken, Spicy gravy, Biryani rice, Salad" },
  { id: "sz3", name: "Chicken Tikka Sizzler", category: "Sizzlers", isVeg: false, calories: 720, price: "470", description: "6 pieces of Chicken Tikka, Spicy gravy, Biryani rice, Salad" },
  { id: "sz4", name: "Paneer Chilly Sizzler", category: "Sizzlers", isVeg: true, calories: 580, price: "420", description: "Chilly paneer in sauce, Veg fried rice, Crispy veg" },
  { id: "sz5", name: "Paneer Schezwan Sizzler", category: "Sizzlers", isVeg: true, calories: 600, price: "440", description: "Paneer in Schezwan sauce, Schezwan fried rice, Crispy veg" },
  { id: "sz6", name: "Paneer Tikka Sizzler", category: "Sizzlers", isVeg: true, calories: 620, price: "440", description: "6 Pieces of Paneer tikka, Biryani rice, Stuffed Capsicum, Salad" },

  // ───── MARINADES (Ready to Cook) ─────
  { id: "m1", name: "Murgh Tikka Marinade", category: "Marinades", isVeg: false, calories: 280, price: "210/425/850" },
  { id: "m2", name: "Murgh Haryali Tikka Marinade", category: "Marinades", isVeg: false, calories: 260, price: "210/425/850" },
  { id: "m3", name: "Murgh Malai Tikka Marinade", category: "Marinades", isVeg: false, calories: 300, price: "220/440/875" },
  { id: "m4", name: "Murgh Afghani Tikka Marinade", category: "Marinades", isVeg: false, calories: 290, price: "210/425/850" },
  { id: "m5", name: "Chicken Tandoori Leg Marinade", category: "Marinades", isVeg: false, calories: 320, price: "340/680" },
  { id: "m6", name: "Amritsari Fish Marinade", category: "Marinades", isVeg: false, calories: 350, price: "250/500/1000", tags: ["Seafood"] },
  { id: "m7", name: "Tandoori Prawns Marinade", category: "Marinades", isVeg: false, calories: 200, price: "375/750/1500", tags: ["Seafood"] },

  // ───── ORIENTAL CHAMBER – STARTERS ─────
  { id: "or1", name: "Chilly Chicken", category: "Oriental", subCategory: "Starters", isVeg: false, calories: 380, price: "300", tags: ["Spicy"] },
  { id: "or2", name: "Honey Chilli Chicken Wings", category: "Oriental", subCategory: "Starters", isVeg: false, calories: 420, price: "320" },
  { id: "or3", name: "Chicken Manchurian (Dry)", category: "Oriental", subCategory: "Starters", isVeg: false, calories: 360, price: "300" },
  { id: "or4", name: "Chicken 65", category: "Oriental", subCategory: "Starters", isVeg: false, calories: 400, price: "320", tags: ["Spicy", "Bestseller"] },
  { id: "or5", name: "Chicken Lemon n Pepper", category: "Oriental", subCategory: "Starters", isVeg: false, calories: 340, price: "300" },
  { id: "or6", name: "Chicken Lollypop (Fry)", category: "Oriental", subCategory: "Starters", isVeg: false, calories: 350, price: "230" },
  { id: "or7", name: "Chicken Lollypop Masala", category: "Oriental", subCategory: "Starters", isVeg: false, calories: 380, price: "270" },
  { id: "or8", name: "Chicken Lollypop in Schezwan Sauce", category: "Oriental", subCategory: "Starters", isVeg: false, calories: 400, price: "260", tags: ["Spicy"] },
  { id: "or9", name: "Crispy Chicken", category: "Oriental", subCategory: "Starters", isVeg: false, calories: 420, price: "300" },
  { id: "or10", name: "Tandoori Chicken Lollypop", category: "Oriental", subCategory: "Starters", isVeg: false, calories: 360, price: "320", tags: ["Tandoor"] },
  { id: "or11", name: "Fish Chilly", category: "Oriental", subCategory: "Starters", isVeg: false, calories: 340, price: "375", tags: ["Seafood"] },
  { id: "or12", name: "Chilly Prawns", category: "Oriental", subCategory: "Starters", isVeg: false, calories: 300, price: "470", tags: ["Seafood"] },
  { id: "or13", name: "Schezwan Tandoori Chicken Wings", category: "Oriental", subCategory: "Starters", isVeg: false, calories: 440, price: "370", tags: ["Spicy"] },
  { id: "or14", name: "Chicken Momo", category: "Oriental", subCategory: "Starters", isVeg: false, calories: 280, price: "140" },
  { id: "or15", name: "Chicken Spring Roll", category: "Oriental", subCategory: "Starters", isVeg: false, calories: 220, price: "150" },
  { id: "or16", name: "Chicken Bhel", category: "Oriental", subCategory: "Starters", isVeg: false, calories: 300, price: "175" },
  { id: "or17", name: "Paneer Chilly", category: "Oriental", subCategory: "Starters", isVeg: true, calories: 380, price: "300" },
  { id: "or18", name: "Schezwan Paneer", category: "Oriental", subCategory: "Starters", isVeg: true, calories: 400, price: "300", tags: ["Spicy"] },
  { id: "or19", name: "Paneer 65", category: "Oriental", subCategory: "Starters", isVeg: true, calories: 360, price: "300", tags: ["Spicy"] },
  { id: "or20", name: "Veg Manchurian", category: "Oriental", subCategory: "Starters", isVeg: true, calories: 340, price: "300" },
  { id: "or21", name: "Gobi Manchurian", category: "Oriental", subCategory: "Starters", isVeg: true, calories: 320, price: "250" },
  { id: "or22", name: "Veg Crispy", category: "Oriental", subCategory: "Starters", isVeg: true, calories: 380, price: "300" },
  { id: "or23", name: "Crispy Corn", category: "Oriental", subCategory: "Starters", isVeg: true, calories: 300, price: "240" },
  { id: "or24", name: "Chilly Mushroom", category: "Oriental", subCategory: "Starters", isVeg: true, calories: 260, price: "230" },
  { id: "or25", name: "Veg Momo", category: "Oriental", subCategory: "Starters", isVeg: true, calories: 240, price: "120" },
  { id: "or26", name: "Veg Spring Roll", category: "Oriental", subCategory: "Starters", isVeg: true, calories: 200, price: "130" },
  { id: "or27", name: "Chinese Bhel", category: "Oriental", subCategory: "Starters", isVeg: true, calories: 280, price: "125" },
  { id: "or28", name: "Honey Chilli Potato", category: "Oriental", subCategory: "Starters", isVeg: true, calories: 320, price: "250" },

  // ───── ORIENTAL – MAIN COURSE ─────
  { id: "om1", name: "Chilly Chicken Gravy", category: "Oriental", subCategory: "Main Course", isVeg: false, calories: 380, price: "185/320", tags: ["Spicy"] },
  { id: "om2", name: "Chicken Manchurian Gravy", category: "Oriental", subCategory: "Main Course", isVeg: false, calories: 360, price: "185/320" },
  { id: "om3", name: "Hot n Sour Chicken Gravy", category: "Oriental", subCategory: "Main Course", isVeg: false, calories: 320, price: "195/330" },
  { id: "om4", name: "Butter Garlic Chicken", category: "Oriental", subCategory: "Main Course", isVeg: false, calories: 420, price: "185/320" },
  { id: "om5", name: "Schezwan Chicken Gravy", category: "Oriental", subCategory: "Main Course", isVeg: false, calories: 400, price: "195/340", tags: ["Spicy"] },
  { id: "om6", name: "Prawn Chilly Gravy", category: "Oriental", subCategory: "Main Course", isVeg: false, calories: 320, price: "280/480", tags: ["Seafood"] },
  { id: "om7", name: "Chicken Salt n Pepper", category: "Oriental", subCategory: "Main Course", isVeg: false, calories: 360, price: "180/320" },
  { id: "om8", name: "Chilly Paneer Gravy", category: "Oriental", subCategory: "Main Course", isVeg: true, calories: 360, price: "185/320" },
  { id: "om9", name: "Schezwan Paneer Gravy", category: "Oriental", subCategory: "Main Course", isVeg: true, calories: 380, price: "195/330", tags: ["Spicy"] },
  { id: "om10", name: "Veg Manchurian Gravy", category: "Oriental", subCategory: "Main Course", isVeg: true, calories: 320, price: "185/320" },
  { id: "om11", name: "Chilly Mushroom Gravy", category: "Oriental", subCategory: "Main Course", isVeg: true, calories: 280, price: "185/320" },

  // ───── NOODLES & FRIED RICE ─────
  { id: "n1", name: "Veg Hakka Noodles", category: "Noodles", isVeg: true, calories: 340, price: "175/260" },
  { id: "n2", name: "Veg Schezwan Noodles", category: "Noodles", isVeg: true, calories: 360, price: "185/285", tags: ["Spicy"] },
  { id: "n3", name: "Veg Chilli Garlic Noodles", category: "Noodles", isVeg: true, calories: 350, price: "180/265" },
  { id: "n4", name: "Veg Burnt Garlic Noodles", category: "Noodles", isVeg: true, calories: 360, price: "185/270" },
  { id: "n5", name: "Veg Triple Schezwan Noodles", category: "Noodles", isVeg: true, calories: 380, price: "210/330", tags: ["Spicy"] },
  { id: "n6", name: "Veg Manchurian Noodles", category: "Noodles", isVeg: true, calories: 370, price: "180/280" },
  { id: "n7", name: "Chicken Hakka Noodles", category: "Noodles", isVeg: false, calories: 420, price: "195/295" },
  { id: "n8", name: "Chicken Schezwan Noodles", category: "Noodles", isVeg: false, calories: 440, price: "200/310", tags: ["Spicy"] },
  { id: "n9", name: "Chicken Chilli Garlic Noodles", category: "Noodles", isVeg: false, calories: 430, price: "200/310" },
  { id: "n10", name: "Chicken Burnt Garlic Noodles", category: "Noodles", isVeg: false, calories: 440, price: "200/310" },
  { id: "n11", name: "Chicken Manchurian Noodles", category: "Noodles", isVeg: false, calories: 450, price: "205/315" },
  { id: "n12", name: "Chicken Triple Schezwan Noodles", category: "Noodles", isVeg: false, calories: 460, price: "225/350", tags: ["Spicy"] },
  { id: "n13", name: "Veg Fried Rice", category: "Noodles", isVeg: true, calories: 340, price: "185/270" },
  { id: "n14", name: "Mushroom Fried Rice", category: "Noodles", isVeg: true, calories: 350, price: "190/285" },
  { id: "n15", name: "Triple Schezwan Fried Rice", category: "Noodles", isVeg: true, calories: 380, price: "195/300", tags: ["Spicy"] },
  { id: "n16", name: "Veg Schezwan Fried Rice", category: "Noodles", isVeg: true, calories: 360, price: "190/280", tags: ["Spicy"] },
  { id: "n17", name: "Veg Manchurian Fried Rice", category: "Noodles", isVeg: true, calories: 370, price: "190/280" },
  { id: "n18", name: "Chicken Fried Rice", category: "Noodles", isVeg: false, calories: 420, price: "190/290" },
  { id: "n19", name: "Chicken Schezwan Fried Rice", category: "Noodles", isVeg: false, calories: 440, price: "195/300", tags: ["Spicy"] },
  { id: "n20", name: "Chicken Triple Schezwan Fried Rice", category: "Noodles", isVeg: false, calories: 460, price: "225/350", tags: ["Spicy"] },
  { id: "n21", name: "Mix Meat Fried Rice", category: "Noodles", isVeg: false, calories: 500, price: "235/365" },
  { id: "n22", name: "Chicken Manchurian Fried Rice", category: "Noodles", isVeg: false, calories: 450, price: "195/300" },
  { id: "n23", name: "Egg Fried Rice", category: "Noodles", isVeg: false, calories: 380, price: "155/240" },
  { id: "n24", name: "Egg Schezwan Fried Rice", category: "Noodles", isVeg: false, calories: 400, price: "160/250", tags: ["Spicy"] },

  // ───── THE RICE BOWL – VEG ─────
  { id: "rb1", name: "Paneer Makhni Bowl", category: "Rice Bowl", subCategory: "Veg", isVeg: true, calories: 320, price: "130/170" },
  { id: "rb2", name: "Paneer Do Pyaza Bowl", category: "Rice Bowl", subCategory: "Veg", isVeg: true, calories: 310, price: "130/170" },
  { id: "rb3", name: "Mutter Paneer Bowl", category: "Rice Bowl", subCategory: "Veg", isVeg: true, calories: 300, price: "130/170" },
  { id: "rb4", name: "Dal Makhni Bowl", category: "Rice Bowl", subCategory: "Veg", isVeg: true, calories: 280, price: "135/175" },
  { id: "rb5", name: "Dal Tadka Bowl", category: "Rice Bowl", subCategory: "Veg", isVeg: true, calories: 260, price: "135/175" },
  { id: "rb6", name: "Amritsari Chole Bowl", category: "Rice Bowl", subCategory: "Veg", isVeg: true, calories: 320, price: "130/170" },
  { id: "rb7", name: "Rajma Masala Bowl", category: "Rice Bowl", subCategory: "Veg", isVeg: true, calories: 330, price: "130/170" },
  { id: "rb8", name: "Aloo Tamatar Bowl", category: "Rice Bowl", subCategory: "Veg", isVeg: true, calories: 260, price: "120/150" },
  { id: "rb9", name: "Veg Manchurian Bowl", category: "Rice Bowl", subCategory: "Veg", isVeg: true, calories: 300, price: "140/180" },
  { id: "rb10", name: "Chilly Paneer Bowl", category: "Rice Bowl", subCategory: "Veg", isVeg: true, calories: 320, price: "140/180" },

  // ───── THE RICE BOWL – NON-VEG ─────
  { id: "rb11", name: "Mutton Curry Bowl", category: "Rice Bowl", subCategory: "Non-Veg", isVeg: false, calories: 380, price: "175/220" },
  { id: "rb12", name: "Murgh Makhni Bowl", category: "Rice Bowl", subCategory: "Non-Veg", isVeg: false, calories: 360, price: "150/180" },
  { id: "rb13", name: "Murgh Do Pyaza Bowl", category: "Rice Bowl", subCategory: "Non-Veg", isVeg: false, calories: 340, price: "150/180" },
  { id: "rb14", name: "Chicken Curry Bowl", category: "Rice Bowl", subCategory: "Non-Veg", isVeg: false, calories: 350, price: "145/185" },
  { id: "rb15", name: "Chilly Chicken Bowl", category: "Rice Bowl", subCategory: "Non-Veg", isVeg: false, calories: 340, price: "145/185" },
  { id: "rb16", name: "Chicken Manchurian Bowl", category: "Rice Bowl", subCategory: "Non-Veg", isVeg: false, calories: 330, price: "145/185" },
  { id: "rb17", name: "Fish Curry Bowl", category: "Rice Bowl", subCategory: "Non-Veg", isVeg: false, calories: 300, price: "130/180", tags: ["Seafood"] },
  { id: "rb18", name: "Egg Curry Bowl", category: "Rice Bowl", subCategory: "Non-Veg", isVeg: false, calories: 280, price: "120/150" },

  // ───── COMBO MEALS – VEG ─────
  { id: "cm1", name: "Paneer Makhni with Jeera Aloo Meal", category: "Combo Meals", isVeg: true, calories: 820, price: "305", description: "Paneer Makhni + Jeera Aloo + Rice + 2 Butter Roti" },
  { id: "cm2", name: "Veg Punjabi, Dal Tadka Meal", category: "Combo Meals", isVeg: true, calories: 780, price: "290", description: "Mix Veg Punjabi + Dal Tadka + Rice + 2 Butter Roti" },
  { id: "cm3", name: "Soya Chaap Makhni with Jeera Aloo Meal", category: "Combo Meals", isVeg: true, calories: 800, price: "285", description: "Soya Chaap Makhni + Jeera Aloo + Rice + 2 Butter Roti" },
  { id: "cm4", name: "Veg Manchurian with Fried Rice Meal", category: "Combo Meals", isVeg: true, calories: 750, price: "269", description: "Veg Manchurian Gravy + Veg Fried Rice + 2pc Mushroom Chilly Dry" },
  { id: "cm5", name: "Veg Manchurian with Veg Noodles Meal", category: "Combo Meals", isVeg: true, calories: 760, price: "290", description: "Veg Manchurian Gravy + Veg Hakka Noodles + 2pc Mushroom Chilly Dry" },
  { id: "cm6", name: "Chilly Paneer with Fried Rice Meal", category: "Combo Meals", isVeg: true, calories: 800, price: "320", description: "Chilli Paneer Gravy + Veg Fried Rice + 2pc Veg Manchurian Dry" },
  { id: "cm7", name: "Paneer Tikka Masala, Dal Makhni Meal", category: "Combo Meals", isVeg: true, calories: 850, price: "320", description: "Paneer Tikka Masala + Dal Makhni + Rice + 2 Butter Roti" },
  { id: "cm8", name: "Veg Biryani Meal", category: "Combo Meals", isVeg: true, calories: 900, price: "330", description: "Veg Biryani + 2pc Paneer Tikka + Raita" },

  // ───── COMBO MEALS – NON-VEG ─────
  { id: "cm9", name: "Butter Chicken with Dal Makhni Meal", category: "Combo Meals", isVeg: false, calories: 920, price: "330", description: "Butter Chicken + Dal Makhni + Rice + 2 Butter Roti", tags: ["Bestseller"] },
  { id: "cm10", name: "Chicken Curry with Dal Tadka Meal", category: "Combo Meals", isVeg: false, calories: 880, price: "330", description: "Chicken Curry + Dal Tadka + Rice + 2 Butter Roti" },
  { id: "cm11", name: "Chicken Tikka Masala with Dal Makhni Meal", category: "Combo Meals", isVeg: false, calories: 950, price: "330", description: "Chicken Tikka Masala + Dal Makhni + Rice + 2 Butter Roti" },
  { id: "cm12", name: "Chilli Chicken with Noodles Meal", category: "Combo Meals", isVeg: false, calories: 900, price: "330", description: "Chilli Chicken Gravy + Chicken Hakka Noodles + 2pc Veg Manchurian Dry" },
  { id: "cm13", name: "Chilly Chicken with Egg Fried Rice Meal", category: "Combo Meals", isVeg: false, calories: 880, price: "330", description: "Chilli Chicken Gravy + Egg Fried Rice + 2pc Veg Manchurian Dry" },
  { id: "cm14", name: "Chicken Overload Meal", category: "Combo Meals", isVeg: false, calories: 980, price: "340", description: "Butter Chicken + 2pc Chicken Tikka + Jeera Rice + 1 Butter Naan", tags: ["Bestseller"] },
  { id: "cm15", name: "Chicken Biryani Meal", category: "Combo Meals", isVeg: false, calories: 1000, price: "340", description: "Chicken Tikka Biryani + 2pc Chicken Tikka + Raita" },

  // ───── THALI MEALS ─────
  { id: "th1", name: "Veg Thali", category: "Thali", isVeg: true, calories: 700, price: "90", description: "Subji + Dal + Rice + Roti + Salad + Papad" },
  { id: "th2", name: "Paneer Thali", category: "Thali", isVeg: true, calories: 780, price: "110", description: "Paneer Gravy + Dal + Rice + Roti + Salad + Papad" },
  { id: "th3", name: "Egg Thali", category: "Thali", isVeg: false, calories: 820, price: "120", description: "Egg Curry + Rice + Subji + Roti + Salad + Papad" },
  { id: "th4", name: "Chicken Thali", category: "Thali", isVeg: false, calories: 900, price: "130", description: "Chicken Curry + Subji + Rice + Roti + Salad + Papad", tags: ["Bestseller"] },
  { id: "th5", name: "Fish Thali", category: "Thali", isVeg: false, calories: 880, price: "140", description: "Fish Curry + Subji + Rice + Roti + Salad + Papad", tags: ["Seafood"] },
  { id: "th6", name: "Mutton Thali", category: "Thali", isVeg: false, calories: 950, price: "160", description: "Mutton Curry + Subji + Rice + Roti + Salad + Papad" },

  // ───── DRINKS / FLUID OUNCE ─────
  { id: "d1", name: "Blue Lagoon", category: "Drinks", isVeg: true, calories: 80, price: "100" },
  { id: "d2", name: "Virgin Mojito", category: "Drinks", isVeg: true, calories: 90, price: "100" },
  { id: "d3", name: "Lemon Iced Tea", category: "Drinks", isVeg: true, calories: 70, price: "100" },
  { id: "d4", name: "Fruit Punch", category: "Drinks", isVeg: true, calories: 120, price: "125" },
  { id: "d5", name: "Milk Shake", category: "Drinks", isVeg: true, calories: 250, price: "130" },
  { id: "d6", name: "Milk Shake with Ice Cream", category: "Drinks", isVeg: true, calories: 320, price: "140" },
  { id: "d7", name: "Fresh Lime Soda", category: "Drinks", isVeg: true, calories: 40, price: "50" },
  { id: "d8", name: "Fresh Lime Water", category: "Drinks", isVeg: true, calories: 20, price: "40" },
  { id: "d9", name: "Tea", category: "Drinks", isVeg: true, calories: 30, price: "20" },
  { id: "d10", name: "Coffee", category: "Drinks", isVeg: true, calories: 50, price: "30" },
];

export const getDisplayPrice = (price: string): string => {
  const parts = price.split("/");
  return `₹${parts[0]}`;
};

export const getMinPrice = (price: string): number => {
  return parseInt(price.split("/")[0]);
};
